### A. REPRODUCIBLE NORMALIZATION PROBLEM

This function generates a 5x5 array of reproducible random integers and normalizes the entire dataset by subtracting the array's mean and dividing by its standard deviation. 

In [20]:
import numpy as np
#This creates the reproducible random 5x5 integer ndarray
np.random.seed(2112) 
X = np.random.randint(10, 101, size=(5, 5))

#This calculates the mean and standard deviation of X.
X_mean = np.mean (X)
X_std = np.std (X)

X_normalized = (X - X_mean)/X_std #This normalizes the array

print("X:\n", X)
print("Normalized X:\n", X_normalized)
print("Mean =", np.mean(X_normalized))
print("Standard Deviation =", np.std(X_normalized))

np.save("X_normalized.npy", X_normalized)

X:
 [[48 11 15 67 21]
 [11 41 13 66 24]
 [71 79 53 67 70]
 [77 35 91 19 96]
 [35 54 37 41 17]]
Normalized X:
 [[ 0.06340841 -1.36714726 -1.2124926   0.79801809 -0.98051059]
 [-1.36714726 -0.20723725 -1.28981993  0.75935442 -0.86451959]
 [ 0.95267275  1.26198209  0.25672675  0.79801809  0.91400909]
 [ 1.18465476 -0.43921926  1.72594609 -1.05783793  1.91926443]
 [-0.43921926  0.29539042 -0.36189192 -0.20723725 -1.13516526]]
Mean = 0.0
Standard Deviation = 0.9999999999999999


### B. CUBES DIVISIBLE BY 4 PROBLEM

This function creates a 10x10 array containing the cubes of the first 100 positive integers and uses Boolean masking to extract only the values that are evenly divisible by 4.

In [21]:
#This creates the first 100 positive integers, cubes them, and reshapes them into a 10x10 array.
C = np.arange(1, 101)**3
C = C.reshape(10, 10)

div_by_4 = C[C%4 == 0] #This is where a Boolean condition is applied to obtain cubed values divisible by 4.

print("Shape of C:", C.shape)
print("Array div_by_4:\n", div_by_4)
print("Number of Selected Elements =", div_by_4.size)

np.save("div_by_4.npy", div_by_4)

Shape of C: (10, 10)
Array div_by_4:
 [      8      64     216     512    1000    1728    2744    4096    5832
    8000   10648   13824   17576   21952   27000   32768   39304   46656
   54872   64000   74088   85184   97336  110592  125000  140608  157464
  175616  195112  216000  238328  262144  287496  314432  343000  373248
  405224  438976  474552  512000  551368  592704  636056  681472  729000
  778688  830584  884736  941192 1000000]
Number of Selected Elements = 50


### C. ABOVE-MEAN SQUARES PROBLEM

This function generates a 6x6 array containing the squares of the first 36 positive integers, calculates the overall mean of the array, and uses Boolean filtering to extract only the elements that are strictly greater than that mean.

In [22]:
#This creates the squares of the first 36 positive integers and reshapes them into a 6x6 array.
S = np.arange(1, 37)**2
S = S.reshape(6, 6)

S_mean = np.mean(S) #This computes the mean of all elements of S.

above_mean = S[S > S_mean] #This uses Boolean filtering to select elements strictly greater than S_mean)

print("S:\n", S)
print("Mean of S:", S_mean)
print("Array above_mean:", above_mean)
print("Number of Selected Elements =", above_mean.size)

np.save("above_mean.npy", above_mean)

S:
 [[   1    4    9   16   25   36]
 [  49   64   81  100  121  144]
 [ 169  196  225  256  289  324]
 [ 361  400  441  484  529  576]
 [ 625  676  729  784  841  900]
 [ 961 1024 1089 1156 1225 1296]]
Mean of S: 450.1666666666667
Array above_mean: [ 484  529  576  625  676  729  784  841  900  961 1024 1089 1156 1225
 1296]
Number of Selected Elements = 15
